### PR TITLE
system Spanish language and pages flex blueprint updates

### PR DESCRIPTION
**Pull request by dani-ooo**

### CODE REVIEW

**Comment by mahagr** [comment]
@dani-ooo FYI, your translations will get lost unless you also update them in Crowdin: https://crowdin.com/project/grav-core

**Comment by dani-ooo** [comment]
i didn’t know. thanks, @mahagr!
i’ve submitted the updates there too.

for future language file commits, do i need to update the translations on Crowdin AND the file in the repository, or is it enough with just Crowdin?

**Comment by dani-ooo** [comment]
should i make a new pull request for 2267077e6355db0e5f1a712be4ba008afa3279f7 only?

**Comment by mahagr** [comment]
I've merged everything, so the fix for the template is already in.

**Comment by dani-ooo** [comment]
i didn’t see it had been merged, sorry! i’m fairly new to contributing to gits.

may ask again about the right process for language file commits: do i need to update the translations on Crowdin AND the file in the repository, or is it enough with just Crowdin?

thanks!

**Comment by mahagr** [comment]
It should be enough to update translation in Crowdin.

**Pull request merged**
