### PR TITLE
[RFR] Iterable Taxonomy

### PR DESCRIPTION
**Pull request by OleVik**
Improves the naive implementation in #2596 and solves #1304, by allowing nested/hierarchical taxonomies. A helper-method recursively iterates through taxonomy fields.

The current one-level taxonomy mapping is kept as standard, but this allows nested setups to work alongside by reducing the taxonomy type to a dot-notation where necessary, and thus does not break `taxonomy.findTaxonomy()`. For example, a Page with this taxonomy defined in FrontMatter:

```yaml
taxonomy:
  categories: academic
  tags: [article, tufte, bogus]
  author:
    - name: "Helmut W. M. Sargeant"
      email: "hwms@bogus.tld"
      url: "https://www.stanford.edu/"
      affiliation:
        department: "Department of Literature"
        organization: "Stanford University"
    - name: "L. Agnes Prinn"
      email: "lap@bogus.tld"
      url: "https://www.yale.edu/"
      affiliation: "Department of Sociology, Yale University"
```

Yields:

```php
array:10 [
  "categories" => array:2 [
    "academic" => array:2 []
    "fiction" => array:1 []
  ]
  "tags" => array:4 [
    "article" => array:2 []
    "bogus" => array:2 []
    "book" => array:1 []
    "tufte" => array:1 []
  ]
  "category" => array:1 [
    "Idea" => array:7 []
  ]
  "tag" => array:1 [
    "Lorem Ipsum" => array:1 []
  ]
  "author.name" => array:2 [
    "Helmut W. M. Sargeant" => array:1 []
    "L. Agnes Prinn" => array:1 []
  ]
  "author.email" => array:2 [
    "hwms@bogus.tld" => array:1 []
    "lap@bogus.tld" => array:1 []
  ]
  "author.url" => array:2 [
    "https://www.stanford.edu/" => array:1 []
    "https://www.yale.edu/" => array:1 []
  ]
  "author.affiliation.department" => array:1 [
    "Department of Literature" => array:1 []
  ]
  "author.affiliation.organization" => array:1 [
    "Stanford University" => array:1 []
  ]
  "author.affiliation" => array:1 [
    "Department of Sociology, Yale University" => array:1 []
  ]
]
```

And so `taxonomy.findTaxonomy({'author.email':'hwms@bogus.tld'})` in Twig and `$this->grav['taxonomy']->findTaxonomy(['author.email' => 'hwms@bogus.tld'])` in PHP are valid. The normal logic of accessing FrontMatter in Twig is still available, eg. `{{ page.taxonomy.author[0].affiliation.organization }}`.

### CODE REVIEW

**Comment by rhukster** [comment]
This is looking pretty solid. Just need to do some testing.

**Comment by OleVik** [comment]
Bah, I created the branch from 1.7, I thought it would route itself correctly.

**Comment by OleVik** [comment]
@mahagr There, corrected the base branch. Thankfully GitHub made that easier than expected.

**Comment by rhukster** [comment]
I have merged and will test fully in 1.7 branch. I think that If there are issues we can fix directly in that branch as it’s in active development anyway.

**Pull request merged**
