### PR TITLE
Add audio support.

### PR DESCRIPTION
**Pull request by namaless**

### CODE REVIEW

**Comment by namaless** [comment]
damn merge branch :(

**Comment by w00fz** [comment]
Yikes! :smile: 
You might want to clean it up or redo it. Also the merge is going to kill the functionality in `Page` that andy added earlier (see `Page::find`), might want to fix that before.

**Comment by namaless** [comment]
yeah i see you can add it, i think is more simple :(

**Comment by namaless** [comment]
manual edit without pull merge indeed.

**Comment by w00fz** [comment]
You should use git flow, you can create a feature and work there so no matter what happens in develop, your changes are still maintained intact.

**Comment by namaless** [comment]
ok for now close this pr, tomorrow when fixed my dev installation send again :(
thanks for now :)

**Comment by w00fz** [comment]
Let me see if I can cherry pick this pull request

**Pull request closed without merging**
