### PR TITLE
Installation?

### PR DESCRIPTION
**Pull request by noawa**
Looks like I have no permission to run "bin/grav install" on my "one.com"-Webspace.
Ist there an other possiblity to install grav?

### CODE REVIEW

**Comment by noawa** [comment]
why closed?

**Comment by w00fz** [comment]
Please don't open PR against a release and as your develop as source. Create a patch feature, make your changes there and then create a PR against our `develop` branch.

**Comment by flaviocopes** [comment]
I closed because you posted a Pull Request, not on purpose I think.

The answer to your question is, download the Grav package from getgrav.org/downloads

**Comment by noawa** [comment]
Okay, thank you

**Pull request closed without merging**
