### PR TITLE
Adds new 'enabled/disabled' filters to bin/gpm index

### PR DESCRIPTION
**Pull request by jgonyea**
This adds some more filters to bin/gpm index

--enabled , -e
Filters and displays only plugins/ themes with configurations set to enabled

--disabled, -d
Filters and displays only plugins/ themes with configurations set to disabled

### CODE REVIEW

**Comment by jgonyea** [comment]
I feel like this is permissions related and not code related.
image

**Comment by w00fz** [comment]
It’s most likely not, we will look at the GitHub actions and investigate tests breaking on pr, don’t worry about it too much, we can still merge. Just hadn’t the chance to go through it yet.

**Comment by jgonyea** [comment]
```
$ git remote -v
origin  git@github.com:jgonyea/grav.git (fetch)
origin  git@github.com:jgonyea/grav.git (push)
upstream        https://github.com/getgrav/grav.git (fetch)
upstream        https://github.com/getgrav/grav.git (push)

$ git fetch upstream

$ git rebase upstream/develop
Successfully rebased and updated refs/heads/develop.

$ git branch feature/gpm-index-enhancements

$ git checkout feature/gpm-index-enhancements

$ git apply /r/patch.diff

```

Runnning `git diff feature/gpm-index-enhancements upstream/develop` results in only the new code I have in this PR.

Let me know if I'm doing something wrong.

**Comment by rhukster** [comment]
I've switched the "tests" token back to GITHUB_TOKEN, so this should work for you guys again now.

**Pull request closed without merging**
