### PR TITLE
Added new GPM index filters for showing enabled and disabled plugins/…

### PR DESCRIPTION
**Pull request by jgonyea**
This adds some more filters to bin/gpm index

--enabled , -e
Filters and displays only plugins/ themes with configurations set to enabled

--disabled, -d
Filters and displays only plugins/ themes with configurations set to disabled

### CODE REVIEW

**Comment by jgonyea** [comment]
Note the extra column 'Installed'.  

## Installed

```
$ bin/gpm index -I

GPM Releases Configuration: Stable

PLUGINS [ 5 ]

Packages table
--------------

+-------+-------------------+------------------+---------+-----------+----------+
| Count | Name              | Slug             | Version | Installed | Enabled  |
+-------+-------------------+------------------+---------+-----------+----------+
| 1     | Problems          | problems         | v2.0.3  | installed | enabled  |
| 2     | Error             | error            | v1.7.1  | installed | enabled  |
| 3     | Markdown Notices  | markdown-notices | v1.1.0  | installed | enabled  |
| 4     | Form              | form             | v4.3.0  | installed | enabled  |
| 5     | Flex Objects      | flex-objects     | v1.0.1  | installed | disabled |
+-------+-------------------+------------------+---------+-----------+----------+

THEMES [ 2 ]

Packages table
--------------

+-------+---------+--------+---------+-----------+----------+
| Count | Name    | Slug   | Version | Installed | Enabled  |
+-------+---------+--------+---------+-----------+----------+
| 1     | Quark   | quark  | v2.0.3  | installed | enabled  |
| 2     | Twenty  | twenty | v1.7.1  | installed | disabled |
+-------+---------+--------+---------+-----------+----------+

You can either get more informations about a package by typing:
    bin/gpm info <package>

Or you can install a package by typing:
    bin/gpm install <package>
```



## Disabled
```
$ bin/gpm index --disabled

GPM Releases Configuration: Stable

PLUGINS [ 1 ]

Packages table
--------------

+-------+---------------+--------------+---------+-----------+----------+
| Count | Name          | Slug         | Version | Installed | Enabled  |
+-------+---------------+--------------+---------+-----------+----------+
| 1     | Flex Objects  | flex-objects | v1.0.1  | installed | disabled |
+-------+---------------+--------------+---------+-----------+----------+

THEMES [ 1 ]

Packages table
--------------

+-------+---------+--------+---------+-----------+----------+
| Count | Name    | Slug   | Version | Installed | Enabled  |
+-------+---------+--------+---------+-----------+----------+
| 1     | Twenty  | twenty | v1.7.1  | installed | disabled |
+-------+---------+--------+---------+-----------+----------+

```

## Disabled

Note the plugins Atools and Podcast, which have local yaml configurations left over from being installed prior, but are still both set to enabled.
```
$ bin/gpm index --enabled

GPM Releases Configuration: Stable

PLUGINS [ 6 ]

Packages table
--------------

+-------+-------------------+------------------+---------+---------------+---------+
| Count | Name              | Slug             | Version | Installed     | Enabled |
+-------+-------------------+------------------+---------+---------------+---------+
| 1     | Atools            | atools           | v0.1.1  | not installed | enabled |
| 2     | Problems          | problems         | v2.0.3  | installed     | enabled |
| 3     | Error             | error            | v1.7.1  | installed     | enabled |
| 4     | Markdown Notices  | markdown-notices | v1.1.0  | installed     | enabled |
| 5     | Form              | form             | v4.3.0  | installed     | enabled |
| 6     | Podcast           | podcast          | v2.1.10 | not installed | enabled |
+-------+-------------------+------------------+---------+---------------+---------+

THEMES [ 1 ]

Packages table
--------------

+-------+--------+-------+---------+-----------+---------+
| Count | Name   | Slug  | Version | Installed | Enabled |
+-------+--------+-------+---------+-----------+---------+
| 1     | Quark  | quark | v2.0.3  | installed | enabled |
+-------+--------+-------+---------+-----------+---------+
```

**Review by mahagr — APPROVED** [review]
Looks good.

**Comment by jgonyea** [comment]
I'm not sure how to re-kick off the test suite.  It looks like the automated tests failed due to an authentication issue

**Comment by w00fz** [comment]
Do a minor commit and it will re-kick off the tests

**Comment by jgonyea** [comment]
@w00fz , I'm still getting errors.

Error: Could not authenticate against github.com

I'm not sure why, though.

**Comment by w00fz** [comment]
I think it's because when you created the PR it was against an older version of the GitHub Actions.

I updated them since then, perhaps try merging develop into your PR so you are up to date with Grav and then push the updated changes of your patch. That should be enough to have this pick up.

**Comment by jgonyea** [comment]
I'll rebase with the latest develop and try again.

**Comment by jgonyea** [comment]
@w00fz Same thing.

**Comment by mahagr** [comment]
@jgonyea There are conflicts with your version and develop.

**Comment by jgonyea** [comment]
I'm going to try this whole thing over again.  I can't seem to get this to work properly, despite running a diff and the only file changes are those noted in the PR.

**Pull request closed without merging**
