### PR TITLE
process_twig and frontmatter.yaml

### LINKED ISSUE #1504: frontmatter.yaml does not respect pages.frontmatter.process_twig setting
Hi,

I have tried to add twig into frontmatter.yaml values (i.e. https://github.com/getgrav/grav/issues/1494), but it looks like it is not processed.

Ive very tentatively made a fix to explore the issue. Can you let me know if it is worth a PR :

https://github.com/the4thamigo-uk/grav/commit/b7e2f2829072055b4bc82124f46876c3c6295843

### PR DESCRIPTION
**Pull request by the4thamigo-uk**
Attempt to resolve this issue. Please check as I am not familiar enough with grav codebase to be confident.

### CODE REVIEW

**Comment by mahagr** [comment]
CC #1504 (no link in the title)

**Comment by the4thamigo-uk** [comment]
I removed it from the title, should I remove from the commit?

**Comment by mahagr** [comment]
Commit is fine, I just needed to see the original issue but couldn't without manual typing :)

**Comment by rhukster** [comment]
Will take a look thanks.  Although i've not had issues with frontmatter not being processed, so need to recreate your issue first.  Do you have a specific example of it not working as expected?

**Comment by flaviocopes** [comment]
The problem is that Twig is not processed in header fields defined in `frontmatter.yaml` (not in the page frontmatter). The PR solves the issue for me.

**Pull request merged**
