### PR TITLE
Update Chinese language

### PR DESCRIPTION
**Pull request by dragonandy**
Update both zh.yaml and zh-tw.yaml 
zh.yaml with Simplified Chinese
zh-tw.yaml with Traditional Chinese

### CODE REVIEW

**Comment by rhukster** [comment]
Thanks for your contributions, but they need to be done in crowdin, as those translation are managed there, and then exported periodically into Grav:  https://crowdin.com/project/grav-core

**Comment by dragonandy** [comment]
sorry for the mistake

**Comment by dragonandy** [comment]
It seens like simplified chinese has 100% translated 
@rhukster Maybe consider merge the completed changes to develop branch?

**Comment by rhukster** [comment]
Yup, i need to do a merge for the next release.

**Pull request closed without merging**
