### PR TITLE
Fixed routing issues with multisite and multilanguage

### LINKED ISSUE #1501: Problem with multisite (using setup_subdirectory.php) and multilanguage
Hi, 

I have been trying to get multilanguage support working with multisite using setup_subdirectory.php. After a lot of frustration, Ive managed to boil it down to this issue :

The script below sets up a multisite environment with a valid english page at http://localhost:8080/test/en/home. However, when I navigate to the root url of the _test_ subsite http://localhost:8080/test, the browser is redirected to http://localhost:8080/en and hence delivers the content of the home page of the **_parent_** site http://localhost:8080/en/home. I would have expected it to redirect to http://localhost:8080/test/en and hence deliver the content of the subsite i.e. http://localhost:8080/test/en/home.

Am I missing some configuration or is this a bug?

Thanks

Andy

P.S. I dont see this issue with setup_subdomain.php, but this is due to the fact that a url such as http://test.domain.com:8080 would be correctly routed to http://test.domain.com:8080/en and hence would correctly deliver the content from the subsite http://test.domain.com:8080/en/home

```bash
wget https://getgrav.org/download/core/grav/1.2.4

unzip 1.2.4
cp setup_subdirectory.php grav/setup.php

cd grav

mkdir -p user/sites/test
cp user/pages/01.home/default.md user/pages/01.home/default.en.md

cat << EOF > user/config/system.yaml

languages:
  supported:
    - en
EOF

cp -r user/plugins user/sites/test/
cp -r user/themes user/sites/test/
cp -r user/pages user/sites/test/
cp -r user/config user/sites/test/

php -S 127.0.0.1:8080 system/router.php &

firefox http://localhost:8080/test
```

### PR DESCRIPTION
**Pull request by mahagr**
Fixes #1501 -- remember to add changelog entry on merge.

### CODE REVIEW

**Comment by mahagr** [comment]
Looks like unit tests do not like my change to move some code to its proper location. I will change it back (soon) and tackle the issue later in 2.0.

**Comment by rhukster** [comment]
I think some of these have been made in 1.4 already, if not, it's too far out of date as it stands.

**Comment by mahagr** [comment]
I have updated the pull request. Looks like we still need these changes, though there may be a better way to do them in v1.4 as I've added some classes which will help on routing.

**Comment by mahagr** [comment]
Closed as there's a new version of this pull request.

**Pull request closed without merging**
