### PR TITLE
Update nginx.conf

### PR DESCRIPTION
**Pull request by mrhein**
if is evil see https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

### CODE REVIEW

**Comment by rhukster** [comment]
Looks good. I will test when I get home from vacation this weekend. Thanks!

**Comment by rondlite** [comment]
the .js javascript header found in example config should be editted to. Otherwise all .json uri's are parsed as files and you can not clear cache of preview your work in the admin panel.

**Comment by rhukster** [comment]
@rondlite can you provide a code snipped with .js fix?

**Comment by rondlite** [comment]
@rhukster soz should have posted with previous post
`location ~ \.js$ {
    add_header  Content-Type    application/x-javascript;
}
`
just add EOL after the .js

also, not sure if is needed but my nginx.conf I made like this (from the caddy example):

`location / {
        try_files $uri $uri/  /index.php?_url=$uri;
          }
`

**Comment by rhukster** [comment]
i've added the updated to try_files manually.

**Pull request closed without merging**
