### PR TITLE
Generate a bare 500 response when errors:display is false. This commi…

### PR DESCRIPTION
**Pull request by Perlkonig**
…t does not remove the Resources folder at this time, though they could conceivably be deleted if this approach was accepted.

Related to Issue #1064

### CODE REVIEW

**Comment by Perlkonig** [comment]
Another option is to leverage the Errors plugin in the `handle()` function, but I didn't have time right this second to test how that might work. I'll try tomorrow. Ideally it would check for a customized 500 page in the Errors plugin and return a bare `Handler::QUIT` otherwise.

**Comment by Perlkonig** [comment]
As far as I can tell, the SimplePageHandler doesn't have access to the surrounding Grav object, so perhaps there is no easy customization possible. But with "error:display" set to false, I think a bare 500 is best anyway.

**Comment by Perlkonig** [comment]
The latest commit cleans up the `Resources` folder and minimizes the `SimplePageHandler.php` file as much as works. My admittedly basic tests seemed to work fine. 

* The principle here is that there is no reason for Grav to waste resources on this. If `system.errors.display` is truly set to false, then don't do anything but emit an empty 500.
* Most (all?) modern web servers already offer a server-level option for customizing error pages.
* I tried numerous methods for leveraging the Errors plugin or some other mechanism, but I couldn't come up with something clean. Again, if `system.errors.display` is false, it's probably best to keep it simple and just return the 500.

Anyway, for your consideration. Thanks for your time!

**Comment by rhukster** [comment]
I think this change would cause a lot of upset people.  The custom error page is not just for 500 errors, it's for anything that Grav would throw an error at.  I think most webserver provided 500 errors are very ugly, and don't provide any information, causing lots of extra detective work.  So i'm really not interested in simply removing that. 

If you can find a way to add toggle an **optional** "let webserver handle" errors, then sure I'll consider that, but not simply removing functionality that is there already.  Changes need to be upgrade-safe and not change fundamental behavior.  They can add, even modify (to a degree) current behavior, but not simply remove it.

**Comment by Perlkonig** [comment]
But I think the point of setting `system.errors.display` to `false` is exactly to *not* "provide any information." The site owner can always set the display to `true` and get a full stack trace.

If you're open a new system setting, then I can do that. Ideally I'd turn `system.errors.display` to a three-option switch, but that's not backwards compatible. It just feels hackish to have a `system.errors.display.no_really` setting :smile:

**Comment by flaviocopes** [comment]
Agree, we cannot remove such functionality, which I consider useful. 
An alternative way would be letting the theme provide a custom error page. Or have the ability to change the strings that provide the error message (which now is hardcoded to english - that way one could remove the error message if desired).

**Comment by Perlkonig** [comment]
I tried finding a way to customize, but apparently the handler needed a standalone HTML page. When the error is called, it means you can't rely on Grav to generate anything. Something blew up. New PR on its way.

**Pull request closed without merging**
