### PR TITLE
Fix composer location method

### PR DESCRIPTION
**Pull request by eschmar**
My previous pull request #191 unfortunately had a small bug - the ``shell_exec`` call returned a string with an ending line break, thus breaking the command. Sorry for the trouble.

### CODE REVIEW

**Comment by w00fz** [comment]
Could you also add a check with `function_exists` to make sure `shell_exec` is available and to prevent possible errors?

**Comment by w00fz** [comment]
Also perhaps `command -v` instead of `which`, more universal and faster!

**Comment by rhukster** [comment]
If you can please implement w00fz ideas (good ones), i'll get this merged too.   Thanks!

**Comment by eschmar** [comment]
Sure, good ideas! Just pushed the changes.

**Pull request merged**
