### PR TITLE
Add user to config

### PR DESCRIPTION
**Pull request by Vivalldi**
I have a feeling that this is too "simple" in that no user specific config is merged with other configs but i stayed away from doing that so that plugin developers can choose whether to use user based config (for example the login plugin redirect) or if the want to use overarching config.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Can you describe the end goal, what will this change allow to do?

**Comment by Vivalldi** [comment]
This will allow user specific config to be retrieved with `config->get('user.field.subfield`);` in the same way that plugin, theme, and site config is grabbed.

That being said it is still possible in plugins to retrieve user config by using `$grav['user']['field']['subfield'];`

**Comment by flaviocopes** [comment]
I think it can be useful, letting @rhukster the final word :)

**Comment by rhukster** [comment]
is this reliable between pages?

**Comment by Vivalldi** [comment]
Between pages? As in, if I log in and then navigate to another page, and then another?

**Comment by rhukster** [comment]
Exactly... i merged it then thought about this as there is not going to be any persistence to the compiled configuration.

**Pull request merged**
