### PR TITLE
Fixes #635 use mv instead of rename as that does not support cross volume operations

### LINKED ISSUE #635: docker : rename(/var/www/html/cache/tmp/Grav-56a5f25571331/getgrav-grav-plugin-relatedpages-97423fe/,/var/www/html/user/plugins/relatedpages): Invalid cross-device link
when i install a plugin i have this error
    bin/gpm install relatedpages
    Preparing to install Related Pages [v1.1.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...  

  [RuntimeException]  
rename(/var/www/html/cache/tmp/Grav-56a5f25571331/getgrav-grav-plugin-relatedpages-97423fe/,/var/www/html/user/plugins/relatedpages): Invalid cross-device link

### PR DESCRIPTION
**Pull request by flaviocopes**
Still TODO:

- [x] Check exec() is not disabled
- [x] Fallback to rename()
- [x] Check on windows

### CODE REVIEW

**Comment by bauer01** [comment]
tested ond Windows 10 x64, with Docker Toolbox v.1.13.0-rc3 and PHP 7 container....no problems here.....problem apears again after checkout back to develop, so PR seems to be working on Windows now

**Comment by bauer01** [comment]
is this ok? when you plan to merge it?

**Comment by flaviocopes** [comment]
I've just requested an additional review from our other team devs 👍

**Comment by rhukster** [comment]
@flaviocopes pls fix that CHANGELOG conflict and we can get this merged.

**Comment by flaviocopes** [comment]
Merged

**Comment by flaviocopes** [comment]
Replaced by https://github.com/getgrav/grav/commit/61005360a5edf718d17de55255950fd37bf66d9a

**Pull request merged**
