### PR TITLE
Allow capitalized usernames if the regex agrees

### PR DESCRIPTION
**Pull request by newbthenewbd**
I don't know the exact motivation behind these uses of `strtolower`, but I believe that the existence of the username regular expression in Grav's config clearly implies that the usernames don't just _have_ to be lowercase, hence this pull request.

### CODE REVIEW

**Comment by newbthenewbd** [comment]
Right, completely forgot about this limitation, I apologize.

Still, the way this currently is implemented, Grav noticeably lowers its chances of being used in any sort of social platform, except possibly one about retro computing, limiting its usage to great-looking, high-performance blogs. Due to that, I believe this should still be somehow fixed.

The best implementation I can spontaneously think about is to prepend the usernames with the character case masks, in an optimal number system, i.e. `2002_xx13375h0073rxx` for `xX13375h0073rXx` because hexadecimal `2002` is binary `0010000000000010`. That shouldn't matter at all for websites which only ever have a few admins registered, while the slightly increased disk usage is certainly a better solution for those who want more. Note also that this seems like a naive implementation, as the numbers could visibly be omitted here, however the intuitively better one might use too much CPU time in the lovely language PHP is, hence needing some tests.

Due to that, I request that this pull request stays open for now, with higher quality commits hopefully appearing soon.

**Comment by mahagr** [comment]
This may help to get started:

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/User/User.php#L206

**Comment by newbthenewbd** [comment]
Please review it again. Note that the bug about usernames not getting saved lowercase has been patched by removing the `!$file->filename()` conditional, which seemed to erroneously return false at all times, however I'm admittedly not exactly sure what it was supposed to do in there.

Thanks!

**Comment by newbthenewbd** [comment]
Whoops, forgot about that one (and totally haven't woken up suddenly realizing this), here we go, hopefully.

**Comment by mahagr** [comment]
Looks much better now. The only thing which I don't like is to remove the filename check as it causes filename to potentially change after every save thus causing the user to duplicate.

**Comment by newbthenewbd** [comment]
Closed due to ~the general mess in this pull request's commits and~ the release of Grav 1.5.0. Should totally make a new pull request for the `develop` branch Soon™.

**Pull request closed without merging**
