### PR TITLE
better nginx config, renamed

### PR DESCRIPTION
**Pull request by simonhaenisch**
This is a better Nginx configuration. I did it as part of creating a page at [getgrav/grav-learn](https://github.com/getgrav/grav-learn) about how to use Grav with Nginx. See issue #247 and PR getgrav/grav-learn#302 

I renamed `nginx.conf` to just `nginx`, because `nginx.conf` is the name of the main Nginx config file and naming it like that could lead to people replacing the main config with this file, which would break the Nginx config. This file is supposed to be copied into `/etc/nginx/sites-available`.

### CODE REVIEW

**Comment by simonhaenisch** [comment]
I just saw that you prefer to have a `feature/` branch instead of directly merging to `develop`. Do you want me to change it, i.e. open a new pull request?

**Comment by flaviocopes** [comment]
Actually, feature branches are cool for moving forward something, internally mostly, but for contributions, GitHub PRs are best in this way - it's mostly the same thing.

**Comment by rhukster** [comment]
will review this during the coming week.  Thanks!

**Comment by simonhaenisch** [comment]
I've done a few improvements (IPv6, deny system files, deny hidden files) and a fix regarding url parameters. Before there was

```nginx
try_files $uri $uri/ /index.php?_url=$uri;
```

First I thought that the `_url` parameter was necessary but after looking into the Grav source code I found out that is not true. So I removed the `?_url=$uri` part, but then got 404 for urls with parameters. Adding a random parameter (like `?foo=bar`) made it work again, but the url parameters where not applied (e.g. image crop), so it seems this always "overrides" the real url parameters, because they are never passed. After some more digging I found the [Nginx Docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#variables) and now I know how to correctly pass the url parameters:

```nginx
try_files $uri $uri/ /index.php$is_args$args;
```

`$is_args` adds the `?` only if there are arguments.

**Comment by simonhaenisch** [comment]
I just read <https://learn.getgrav.org/hosting/vps/digitalocean#configure-nginx-connection-pool> and there the thing with `try_files` also needs to be fixed.

**Comment by rhukster** [comment]
Yah I was going to review this nginx conf and merge it with the docs next.

**Comment by rhukster** [comment]
I also prefer to to use user/group for nginx permissions whenever possible for simplicity

**Comment by simonhaenisch** [comment]
Sry, what do you mean by that?

**Comment by simonhaenisch** [comment]
any updates on this, will the PR be merged eventually? I'd like to get rid of my fork one day :nerd_face: 

I don't get why it failed the check, is it possible to re-run the test?

**Pull request closed without merging**
