### PR TITLE
Added resumable download support

### PR DESCRIPTION
**Pull request by Sommerregen**
Hi @rhukster,

this PR adds a resumable download support into Grav. It supports a download limit as well as a qualitity parameter called `download.balance` to tune the download rate (num flushes versus memory size used for buffering). Further it polishes the `getMimeType` method (having speed in mind) and adds support for more mime types.

### CODE REVIEW

**Comment by rhukster** [comment]
This is interesting benny.  One thing I would like to see before merging, is that this be off by default and something you can enabled. Resumable downloads are great for large files, but the download() method is also used to download/send other files including images.  it needs to work optimally and fast for small files too.  There's a lot of work going on here to support the resumable that is only going to add overhead in the majority of cases.

**Comment by Sommerregen** [comment]
Alright I will add another option in the config and/or param to the method and change the behaviour to off by default. Concerning small and large files, I considered both. Small files are almost sent to the browser in one flush (this depends on the `chunk_size` when no download rate is given). You can try it. 

But I totally understand your point. Most of the code is needed to handle all kinds of byte ranges. The rest can be done in a few lines. Thus, I will refactor the code and break it in at least two methods to reduce the overhead (one fast one for downloading only and the other one for supporting resumable downloads).

**Comment by rhukster** [comment]
Sounds great! Thanks.

**Comment by mahagr** [comment]
Wow, nice work on this one! You even added parameter to change the filename what user will see. Will be great especially if you want to support protected downloads (with hashed filenames).

**Comment by Sommerregen** [comment]
Dear @rhukster, as already mentioned in the chat, the best option concerning performance of the core and extensibility would be to release my changes as an own plugin. I think the basics are already present in core. For doing this I will use the `onBeforeDownload` event and add some stuff there.

Thanks, for the good discussion here! :-D

**Pull request closed without merging**
