### PR TITLE
[Ready to merge] Allow subfolder url rewrite

### PR DESCRIPTION
**Pull request by flaviocopes**
By setting `custom_base_url` in system.yaml, we can have Grav in a subfolder but run it in the domain root.

## Scenario 1

Grav is installed in `http://localhost:8080/grav-develop` but you want it to respond on `http://localhost:8080`

In system.yaml, set

```
custom_base_url: 'http://localhost:8080'
```

and set the session path to the new Grav site path, 

```
session:
  path: /
```

And in the domain root, set the redirect, e.g. with .htaccess:

```
RewriteEngine On
RewriteCond %{REQUEST_URI} !^/grav-develop/
RewriteRule ^(.*)$ /grav-develop/$1
```

where `grav-develop` is the subfolder where Grav is.

## Scenario 2

Grav is installed in `http://localhost:8080/grav-develop` but you want it to respond on `http://localhost:8080/xxxxx`

In system.yaml, set

```
custom_base_url: 'http://localhost:8080/xxxxx'
```

and set the session path to the new Grav site path, 

```
session:
  path: /xxxxx
```

And in the new root folder, /xxxxx, set the redirect, e.g. with .htaccess:

```
RewriteEngine On
RewriteCond %{REQUEST_URI} !^/grav-develop/
RewriteRule ^(.*)$ /grav-develop/$1
```

where `grav-develop` is the sister subfolder where Grav is.

### CODE REVIEW

**Comment by rhukster** [comment]
We should add at least an empty config entry in `system.yaml`, also the blueprint should be updated to allow these to be set from admin.

**Comment by flaviocopes** [comment]
This PR currently has a problem with Admin and it cannot login for "Invalid security token" as for some reason session_id() returns two different values before logging in and while trying to login, investigating.

**Comment by w00fz** [comment]
Is it safe to delete  ⬆️ this branch?

**Comment by flaviocopes** [comment]
Yes, removed

**Pull request merged**
