### PR TITLE
Feature/more options gpm #892

### PR DESCRIPTION
**Pull request by rebangm**
Hello,

This PR add options to update only plugins or themes when you 're running bin/gpm update.
Only plugins : bin/gpm update --plugins
Only themes : bin/gpm update --themes

PR Idea from issue https://github.com/getgrav/grav/issues/892, when PR merged fixes https://github.com/getgrav/grav/issues/892

PS : I don't know codeception, and there is no command Test, so I don't write UpdateCommandTest.

Bye

### CODE REVIEW

**Comment by Vivalldi** [comment]
What happens if you don't pass an argument?

Just by briefly looking at it, there is no logic to handle if neither is set

**Comment by rebangm** [comment]
Yes, you're right, i need to handle when none of two options are set.
I'll fix it.

Thx

**Comment by rebangm** [comment]
@Vivalldi change done, same behavior like I said previously and now 
```bin/gpm update ``` -> update plugins and themes

**Comment by Sommerregen** [comment]
@rebangm Nice! However your code currently does not conform with the PSR0/2 standards (see http://www.php-fig.org/psr/psr-2/). Can you change that, too?

**Comment by rebangm** [comment]
@Sommerregen I'll check my IDE, I have PSR-2 configuration, maybe a mistake from me 
I'll use Php-CS-Fixer to check.

Thx

**Comment by rebangm** [comment]
@Sommerregen Done, my bad !! I don't put my pre-commit git hook for PSR-2 compliant.
lots of lines changed with my hook, not only my code.
Tell me if I revert commit and fix PSR-2 only on my code.

Thx

**Comment by Sommerregen** [comment]
@rebangm Having a Php-CS-Fixer run in the background is fine and I like it. However @rhukster is the man who has decide it on the very end.

As I told you I'll check the code. If everything is fine and @rhukster back he will then merge it to the core.

P.S.: @rhukster Would be fine to run Php-CS-Fixer as a hook to the Grav repository, too!

**Comment by Vivalldi** [comment]
Well there are a few things that break out of standard for readability, such as,
```
$someArray['withKey`]              = 'value';
$someArray['withAnotherKey']  = 'anotherValue';
```
The fixer is going to change it to simply be
```
$someArray['withKey`] = 'value';
$someArray['withAnotherKey'] = 'anotherValue';
```

The code works fine for me 👍

**Comment by flaviocopes** [comment]
Fine for me!

**Pull request merged**
