### PR TITLE
Add CSS media attribute

### PR DESCRIPTION
**Pull request by Sommerregen**
This PR adds the ability to set custom media attributes to CSS stylesheets via e.g. 

```twig
{{ do assets.addCss('theme://css/print.css', 100, null, 'print') }}
```

### CODE REVIEW

**Comment by rhukster** [comment]
Could you rewrite this to use the array attribute style rather than override the method signature. I recently updated these methods to support arrays, and this is the better way to add new features and functionality.

**Comment by rhukster** [comment]
Oh actually you did, i think we just not include it in the method signature.

**Comment by Sommerregen** [comment]
Can you clarify this point? You mean https://github.com/getgrav/grav/pull/335/files#diff-036bc801ec8840ea4247592b9ded7a66R267 ?

Ahh, again an undocumented feature. You mean using it via, 

```php
$grav['assets']->addCss('mytheme.css', ['media' => 'screen']);
```

supersedes my PR.

**Comment by rhukster** [comment]
Yes, I documented it last week actually: http://learn.getgrav.org/themes/asset-manager#options

**Comment by Sommerregen** [comment]
Ah, too bad... Will close it.

**Comment by rhukster** [comment]
Oh no, it doesn't supercede your PR, it does not add random attributes.  Your PR bit that takes the value from the array and adds it in the HTML is still valid. Just I don't want to add these to the method signature as we find more things to add.

**Comment by Sommerregen** [comment]
Ok, and what should I gonna do? Leave it open for moment? Change the code?

**Comment by rhukster** [comment]
Yah change the code and remove the method signature changes, and just check to see if its in the array, and if it is, add it to the HTML as you have it.

**Comment by Sommerregen** [comment]
Ok, done!

**Comment by rhukster** [comment]
Just minor, when you get $media from the array, if it's empty you are setting $media to a space, won't this add an extra space that is not needed?

**Comment by Sommerregen** [comment]
Yah, you are right. Can you correct this after merging?

**Comment by rhukster** [comment]
yah no problem

**Pull request merged**
