### PR TITLE
Add Grav version to PHPdebugbar

### PR DESCRIPTION
**Pull request by hughbris**
Adds "Grav v*x.y.z*" as first line info to Messages tab on debug bar

### CODE REVIEW

**Comment by hughbris** [comment]
Sheesh, sorry about those old commits, that was me trying to sync my fork with upstream. Guess I did that wrong.

**Comment by hughbris** [comment]
Oh man, failed integration test, this is when Github just gets in the way. What do you recommend, a rebase? just delete my old fork and fork again? would not be an issue if it would allow me to create a second fork.

Or can you somehow work with this?

What I did to get to this point is:
* cloned my fork repo
* added upstream remote
* fetched and merged my clone with upstream
* pushed to origin (my fork)
* committed changes, pushed to my fork

**Comment by rhukster** [comment]
I think it failed due to a 'blip' on travis.. try another dummy commit to kick off another test.

**Comment by hughbris** [comment]
Starting to really dislike that Travis guy ..

Forgot about GH inline edits, so abandoning this and refer https://github.com/getgrav/grav/pull/2106

**Pull request closed without merging**
